export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './conversationController.service';
import { ConversationControllerService } from './conversationController.service';
export * from './friendsController.service';
import { FriendsControllerService } from './friendsController.service';
export * from './messageController.service';
import { MessageControllerService } from './messageController.service';
export * from './serverController.service';
import { ServerControllerService } from './serverController.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './voiceController.service';
import { VoiceControllerService } from './voiceController.service';
export const APIS = [AuthenticationService, ConversationControllerService, FriendsControllerService, MessageControllerService, ServerControllerService, UsersService, VoiceControllerService];
