spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/null_Project
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/null_chat?authSource=admin

  mail:
    host: localhost
    port: 1025

  kafka:
    bootstrap-server: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: null-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.demo.message"

application:
  security:
    jwt:
      secret-key: 038fa2ffaaed1d2613c42f3ed23fb661cd77e0ac8eec0b14
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:
    allowed-origins: htpp://localhost:4200

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8088