services:
  postgres:
    container_name: postgres-sql-null
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: null_Project
    volumes:
      - postgres:/data/postgres
    ports:
      - 5431:5432
    networks:
      - null-network-project
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-null
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_DEFAULT_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - null-network-project
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-null
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  mongodb:
    image: mongo:latest
    container_name: null_mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    networks:
      - null-network-project

  kafka:
    image: apache/kafka:latest
    container_name: null_kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' # Un ID cualquiera para que formatee su disco
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - null-network-project

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    # 🚀 Agregamos --node-ip para que el servidor sepa exactamente quién es
    command: --dev --bind 0.0.0.0 --node-ip 127.0.0.1
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "50000-50050:50000-50050/udp"
    restart: unless-stopped
    networks:
      - null-network-project

networks:
  null-network-project:
    driver: bridge

volumes:
  mongo_data:
  pgadmin:
  postgres:
    driver: local