/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemberResponse } from './memberResponse';
import { ChannelResponse } from './channelResponse';


export interface ServerResponse { 
    id?: number;
    name?: string;
    imageUrl?: string;
    channels?: Array<ChannelResponse>;
    members?: Array<MemberResponse>;
}

