name: Monorepo Linting CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. Revisa el Backend (Java)
  lint-backend:
    name: Lint Java Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Ejecutar Checkstyle
        run: mvn checkstyle:check -f ./null_services_backend/pom.xml

  # 2. Revisa el API Gateway (Java)
  lint-gateway:
    name: Lint Java Gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Ejecutar Checkstyle
        run: mvn checkstyle:check -f ./null_services_gateway/pom.xml

  # 3. Revisa el Frontend (Angular)
  lint-frontend:
    name: Lint Angular Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./null_services_frontend
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.13.0'
          cache: 'npm'
          cache-dependency-path: ./null_services_frontend/package-lock.json
      - name: Instalar dependencias
        run: npm ci
      - name: Ejecutar Linter de Angular
        run: npm run lint